### ISSUE TITLE
Please push new version to hex

### ISSUE THREAD

**Issue by sebastian** [tungd/elixir-dns#1]
Hi,
the version (`0.0.3`) on hex doesn't yet have the `socket` dependency, and therefore doesn't build. The `master` version in this repo on the other hand does.

Do you think you could please push an updated version to `hex`?

Thank you!

Sebastian

**Comment by tungd** [comment]
Hi, it's just that the dependency was `git', as at the time I was waiting for my patch to get `socket' working with Elixir 1.2 merged. I've pushed a new version (0.0.4) with proper dependency. 

Thanks.
