### ISSUE TITLE
Add example of how to use the server to send return codes

### ISSUE THREAD

**Issue by doug-co** [tungd/elixir-dns#11]
I've been playing with the examples, and from looking at the readme, it isn't clear how I would return a not found or server error return code to a request.

I think it would be helpful to have an example.

Thanks!

**Comment by doug-co** [comment]
With a little more study of the code, my solution is as follows:

replace:

```elixir
%{record | anlist: [resource]}
```

with:

```elixir
case rcode do
  0 -> %{record | anlist: [resource]}
  _ -> %{record | header: %{ record.header | rcode: rcode }}
end
```

rcode is set at some point in the handle function to based on the server's response to the query.

If you think this would be helpful to others, please add to the README.md

**Comment by tungd** [comment]
Hi, this is just basic record update, I think people who are familiar with Elixir can figure this out themselves.
