### ISSUE TITLE
Clarify that you need the Erlang sources to compile this library

### ISSUE THREAD

**Issue by arjan** [tungd/elixir-dns#15]
It would be nice if the README could state that you need the Erlang/OTP source files to compile this library. On Ubuntu, without the `erlang-src` package, I get the following error:

```
== Compilation error in file lib/dns/header.ex ==
** (RuntimeError) error parsing file /usr/lib/erlang/lib/kernel-5.4/src/inet_dns.hrl, got: {:error, :enoent}
```

because the `src` directory is missing from the kernel application.

**Comment by ghenry** [comment]
Just hit this installing on Ubuntu as per https://elixir-lang.org/install.html#distributions
