### ISSUE TITLE
Warning when using with dig

### ISSUE THREAD

**Issue by jveiga** [tungd/elixir-dns#27]
Hi, I was trying out this library and querying with dig, 
for example:
```bash
$ dig @localhost -p 8000 facebook.com
;; Warning: query response not set
....
```
from reading online, it means I'm missing a field called `QR`

Where should I set it?

**Comment by tungd** [comment]
Hi, I've updated the test server example. Particularly:

```elixir
%{record | anlist: [resource], header: %{record.header | qr: true}}
```

The DNS spec requires `qr` bit on DNS.Header set to distinguish between query and response.
