### ISSUE TITLE
Tag 2.1.3

### ISSUE THREAD

**Issue by ruudk** [tungd/elixir-dns#33]
When I follow the docs I get:
```
mix deps.get
** (Mix) No matching version for dns ~> 2.1.3 (from: mix.exs) in registry

The latest version is: 2.1.2
```

**Comment by tungd** [comment]
Hi @ruudk, I'm terribly sorry it took me so long to handle this. I was holding the release hoping that I could also get the DNS over HTTP library ready. Nevertheless, the latest version of the library has been updated to v2.2.0 and is available on Hex.
