### ISSUE TITLE
Function clause error in simple DNS resolve

### ISSUE THREAD

**Issue by cronokirby** [tungd/elixir-dns#4]
This is possibly an issue with the underlying Socket library, instead of this one.
```
iex(1)> DNS.resolve("google.com")
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Socket.arguments/1
             lib/socket.ex:170: anonymous fn(:binary) in Socket.arguments/1
    (elixir) lib/enum.ex:966: Enum.flat_map_list/2
    (elixir) lib/enum.ex:967: Enum.flat_map_list/2
             lib/socket/udp.ex:150: Socket.UDP.arguments/1
             lib/socket/udp.ex:81: Socket.UDP.open/2
             lib/socket/udp.ex:89: Socket.UDP.open!/2
             lib/dns.ex:24: DNS.query/2
             lib/dns.ex:10: DNS.resolve/2
```
using `0.0.4`, I get this for a simple dns resolve. Similar results for other urls.

**Comment by tungd** [comment]
I will look into it, thanks!

**Comment by cronokirby** [comment]
After adding the github repo directly as a dependency, this is solved. I think you might've bumped up the socket dep between 0.0.4 and now, leaving an out of date Socket dependency on hex.pm.

**Comment by tungd** [comment]
I've publish a new version with updated `socket` dependency.
