### ISSUE TITLE
Idea: Split DNS into two parts

### ISSUE THREAD

**Issue by Raphexion** [tungd/elixir-dns#40]
Dear Elixir-DNS,

Would it make sense to split this package into two? One with the passive code (structs and so on) and one with the more active code (server).  Maybe the could be called dns-core and dns.

Pros:
- Make the core part more reusable
- The core package could drop the socket dependency

Cons:
- This project is fine like it is - why complicate things

Kind regards
Niklas

**Comment by tungd** [comment]
Hey, thanks for the comment. I don't really see any reason to do it just yet, given that `socket` is an excellent library. Still, I'm open to this, if there's more demand.

**Comment by Raphexion** [comment]
@tungd Thank you for reading and giving feedback on my idea. I think you have a very valid point. Let's do like you suggest :sunny:
